//
// ExchangeRatesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ExchangeRatesAPI {
    /**
     Get BTC-to-Currency exchange rates

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func exchangeRatesGet(completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        exchangeRatesGetWithRequestBuilder().execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Get BTC-to-Currency exchange rates
     - GET /exchange_rates


     - returns: RequestBuilder<Void> 
     */
    open class func exchangeRatesGetWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/exchange_rates"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
